In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel('Query_complete.xlsx')
df1_sub1 = pd.read_csv('Trial_dataset1_10000_with_GoogleReviews.csv')
df1_sub2 = pd.read_csv('Trial_dataset10001_20000_with_GoogleReviews.csv')

In [3]:
df1.head(10)

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,NaN,NaN
1,SC402065,4.2,1.0,NaN,NaN
2,SC444940,4.6,NaN,NaN,NaN
3,SC857241,4.7,2.0,NaN,NaN
4,11215147,4.8,NaN,NaN,NaN
5,16519529,4.6,1.0,NaN,NaN
6,16379120,4.5,1.0,NaN,NaN
7,SC531326,4.6,2.0,NaN,NaN
8,8589456,5.0,NaN,NaN,NaN
9,15478214,4.6,NaN,NaN,NaN

In [4]:
df1.isna().sum()

 CompanyNumber                          0
Google_Overall_Rating                   0
Google_Price_Level                  10290
Google_Review_Texts                 15659
Google_Individual_Review_Ratings    15659
dtype: int64

In [5]:
df1_sub1.head(10)

,CompanyNumber,CompanyName,RegAddress.PostCode,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,SC780693,M&S MAZZONI,PA145ED,4.7,NaN,Highly Recommended – M-Brothers Automotive Bri...,5 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SC402065,LIGHTHOUSE BAR,PA151DG,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SC444940,RISTORANTE ARLECCHINO,PA151XG,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SC857241,AF EATS,PA169AP,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11215147,THE GATE INN CO.,DE551AQ,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16519529,CLIFFINN,DE45DP,4.6,1.0,Great little country pub. Super staff / owners...,5 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16379120,KASHMIR 1,GL522LH,4.5,1.0,Very good food and taste Lovely lads from mir...,5 | 4 | 5 | 5 | 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SC531326,SPICE GARDEN STIRLING,FK82LT,4.6,2.0,We were intrigued by a face book post that Spi...,4 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8589456,TUMAN CATERING,CR07RB,5.0,NaN,| |,5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,15478214,RIZGAR,CR52NG,4.6,NaN,I want to say how happy I am with Dobles. A co...,5 | 5 | 5 | 5 | 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df1_sub2.head(10)

,CompanyNumber,CompanyName,RegAddress.PostCode,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,12839866,CASA PARMO,B128JY,3.9,NaN,Whilst I respect and understand that I’m leavi...,1 | 5 | 5 | 5 | 1
1,16555427,GOLDEN 88 RB,B448NQ,4.0,NaN,My family orders from here at least once a mon...,2 | 2 | 5 | 5 | 5
2,12901062,HNA BROTHERS,B296JE,NaN,NaN,NaN,NaN
3,NI680239,BAY OF BENGAL,BT808EE,4.2,NaN,I tested the doner kebab in naan bread with sa...,4 | 5 | 5 | 5 | 1
4,15816064,YUMMIES TAKE AWAY,NE15RG,4.0,NaN,We’re regular customers here but the last 2 ti...,2 | 5 | 1 | 5 | 5
5,13598597,LUCKYTEA 0086,SW82FR,4.3,NaN,I thoroughly enjoyed the grape lemon tea; it w...,4 | 3 | 5 | 5 | 5
6,12162967,PICAPAU RESTAURANT,PE301EJ,4.6,NaN,"The food is always fresh, full of flavour and ...",5 | 5 | 5 | 5 | 5
7,14984903,YUMMY 588,WF75EG,3.8,1.0,Absolutely the worst chinese we've ever had! I...,1 | 1 | 5 | 1 | 5
8,SC813888,AULD HOOSE PUB 30,ML28NN,4.5,NaN,Good mix of Celtic and Rangers fans watching t...,4 | 5 | 5 | 4 | 5
9,12916416,GRIFFIN CAFE,CM187BL,4.8,NaN,A nice quiet hidden place just to take a break...,5 | 5 | 5 | 5 | 5

In [7]:
df1_sub1.columns

Index([' CompanyNumber', 'CompanyName', 'RegAddress.PostCode',
       'Google_Overall_Rating', 'Google_Price_Level', 'Google_Review_Texts',
       'Google_Individual_Review_Ratings', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [8]:
df1_sub1 = df1_sub1[[' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings']]

In [9]:
df1_sub1.head(10)

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,Highly Recommended – M-Brothers Automotive Bri...,5 | 5 | 5 | 5 | 5
1,SC402065,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5
2,SC444940,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5
3,SC857241,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4
4,11215147,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5
5,16519529,4.6,1.0,Great little country pub. Super staff / owners...,5 | 5 | 5 | 5 | 5
6,16379120,4.5,1.0,Very good food and taste Lovely lads from mir...,5 | 4 | 5 | 5 | 4
7,SC531326,4.6,2.0,We were intrigued by a face book post that Spi...,4 | 5 | 5 | 5 | 5
8,8589456,5.0,NaN,| |,5 | 5 | 5
9,15478214,4.6,NaN,I want to say how happy I am with Dobles. A co...,5 | 5 | 5 | 5 | 5

In [10]:
df1_sub2 = df1_sub2[[' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings']]

In [11]:
df1_sub2.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,12839866,3.9,NaN,Whilst I respect and understand that I’m leavi...,1 | 5 | 5 | 5 | 1
1,16555427,4.0,NaN,My family orders from here at least once a mon...,2 | 2 | 5 | 5 | 5
2,12901062,NaN,NaN,NaN,NaN
3,NI680239,4.2,NaN,I tested the doner kebab in naan bread with sa...,4 | 5 | 5 | 5 | 1
4,15816064,4.0,NaN,We’re regular customers here but the last 2 ti...,2 | 5 | 1 | 5 | 5

In [12]:
df1_sub = pd.concat([df1_sub1, df1_sub2]).drop_duplicates(keep=False)

In [13]:
len(df1_sub)

19999

In [14]:
len(df1_sub1)

9999

In [15]:
len(df1_sub2)

10000

In [16]:
len(df1)

15659

In [17]:
df1.set_index(' CompanyNumber', inplace=True)
df1_sub.set_index(' CompanyNumber', inplace=True)

# 2. Overwrite df1 with values from df2
df1.update(df1_sub)

# 3. Reset index to bring 'place_id' back as a column
df1.reset_index(inplace=True)

C:\Users\hdar0\AppData\Local\Temp\ipykernel_13784\3849299077.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Highly Recommended – M-Brothers Automotive Brilliant experience with M-Brothers Automotive. Very experienced and knowledgeable team who clearly know what they’re doing. Customer service was excellent from start to finish, and the prices were very reasonable for the quality of work provided. Honest, reliable, and professional — I’ll definitely be using them again and highly recommend them to anyone needing vehicle repairs. | Outstanding Service and Incredible Trustworthiness!  I cannot recommend M-Brothers Automotive highly enough. I recently brought my car in for a major service that included a full service, ball joint replacement, and a rear differential service. From start to finish, the experience was flawless.  The team was professional, knowledgeable, and took the time to explain exactly what needed to be done and why. Their pricing was fair and transparent, with no surprise charges.  The work was completed efficiently and my car is now running smoother and quieter than it has in years. The real standout moment, however, was when they mentioned they noticed one of my headlights was dim and they replaced it for me free of charge, on the house! | Very happy with the service I received. The car was serviced professionally and they carried out a free health check where they picked up a few issues and explained everything clearly. Honest, knowledgeable, and great customer service. Would definitely recommend. 👍 | I had an excellent experience getting my car serviced here. I came in for an oil change/diagnostic and the team was professional, honest, and very efficient. The staff explained everything clearly and didn’t try to upsell unnecessary work. My car runs perfectly now, and the whole process was quick and stress-free. Special thanks to IBZ for the great service. Highly recommend this place to anyone looking for reliable car care! | Its hard to find good garages in bham, however this specific garage, outstanding service and quick shout out to the brother(Ibz) ibrahim. May allah make you happy man,the way u made me happy man, ameen.'
 "Small but friendly establishment. Couple of TV's showing the World Cup and this was followed by karaoke. Carling lager on draft. Good atmosphere. | Allowed the maukinhill team into pub to enjoy their cup final win and service was good | Had a unplanned evening in here on a Friday night . Karaoke omg what a fab wee bar . Bar staff was so lovely . Karaoke presenter was fab also heavily pregnant and loving life . We had the best night . Thank u so much for making us feel so welcomed .  We didn't have food never seen mentioned anywhere but was a fab night as a surprise meal and pub crawl with my friends for my 50th one turning 60 . Highly recommend x | The staff here were incredibly rude and unpleasant. Add to that the overpriced drinks, the uncomfortably loud music and the lack of seating and this isn't somewhere I would ever want to find myself again.  Its only redeeming feature was the fairly pleasant patrons, none of whom gave us the slightest bit of trouble (we had left another Greenock bar earlier in the evening as one of the customers had a bit too much to drink and was becoming aggressive towards the staff). | The Lighthouse is pure unpretentious Greenock.  I love it.  It looks like it once was a cafe where they spent £20 on turning it into a pub, but the bar staff are lovely, the patrons are friendly and a good night is the most likely outcome - especially on their karaoke nights which are brilliant."
 'The best vegan pizza in Inverclyde! Absolutely loved it! Generous toppings, high quality pizza base, yummy vegan cheese. Loved the friendly service and reasonable prices. I will be back soon! | Here is what to get - Chips, Bolognese and Cheese for takeaway. It is my mother and I’s go to. Affordable, extremely delicious. You will be quickly served, with kind faces. I highly recommend coming here, whether you are sitting in, or having a takeaway. When sitting in, you have natural lighting, which is especially good on a sunny day. Hope to come here again soon. Thank you! | We love it here and the staff are really pleasant and always give us wonderful service. We’ve always enjoyed the food we have ordered and recently been loving their coffee and homemade cakes too. Michelle and all the other staff are so friendly and nothing is ever a bother to them. An old favourite that’s been back to the top of our list these past few months :-) | Went to get a takeaway tonight, can I just say the young guy serving was brilliant, very polite and friendly with everyone who came in | The Arlecchino is a fantastic italian in Greenock. We\'re so happy to have found it yesterday. We always walked by because we didn\'t noticed the entrance. The atmosphere is amazing. Very bright and light and colourful decorated. The food was delicious. Ken died for his lasagne and I carved in my "Haddock Meuniere, unbuttered, and in white wine, lemon and parsley sauce with veg, chips or potatoes. The carrot cake with pecan nuts was beautiful. We will definitely come back soon!'
 ...
 "Excellent meat got from here. Staff was also very friendly and helpful. | I have been using this Butcher shop for many many years, I love it because the staff are friendly, the shop is clean and always has been over the years. I give the staff, the meat and the shop itself a 10 out of 10. | Very friendly staff, great quality halal meat, and sell a variety of other groceries and vegetables too. | Was served  by a friendly man,clean away the fat and made it nice. Aways friendly that's why I go to that Halal Meat shop. | Staff are always pleasent and friendly, great place to shop with an impresive variety of stock."
 'Went to a  Christmas lunch .  Had prawn cocktail,  turkey and Christmas pudding.   It was all delicious.  The service was good and it was good value for money. | Went for Sunday lunch with my grandson, Oliver, was greeted by Nathan, who was very attentive during our time there. We had the Duo Roast Lunch, which was Beef & Turkey. This was excellent. My complements to the Chefs, Neil & Mark on the presentation & quality of the food. I highly recommend Bridges Restaurant & will definitely be returning. | Absolutely loved the Duo Sunday lunch.  Food was fantastic and service was wonderful.  Such a lovely location. | More seasoning needed | '
 'I had a party ordered this from Southam pizza the quality is sky high | Excellent local Pizza takeaway with a great range of pizzas, chicken meals, burgers, dips & deserts. Quick service & useful low cost delivery within 3miles radius. | My chicken and chips were great. Sauce was tasty, a bit like Pepes in Leamington, and the chicken wasn’t dry. Chips were a bit cold but we were a little late to collect. | Amazing foods, made with loads of love. Love the friendly staff and generous portions, love the really affordable meal deals as well. Great, great stuff! 🔥. | Hands down best takeaway I have ever had! From taste, to warmth, to quality & quality. Friendly delivery service, reasonable delivery charges, food was piping hot & SO much of it. 1/4 chicken, coleslaw, 12" pizza, portion of chips, garlic dip - £23 Inc delivery. Only downside is it shuts quite early for a takeaway place. Hope the quality & service stays consistent 🙏']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.update(df1_sub)
C:\Users\hdar0\AppData\Local\Temp\ipykernel_13784\3849299077.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['5 | 5 | 5 | 5 | 5' '5 | 5 | 5 | 1 | 5' '5 | 5 | 5 | 5 | 5' ...
 '5 | 5 | 5 | 5 | 5' '5 | 5 | 5 | 4 | 4' '5 | 5 | 5 | 5 | 5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.update(df1_sub)

In [18]:
df1.head(10)

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,Highly Recommended – M-Brothers Automotive Bri...,5 | 5 | 5 | 5 | 5
1,SC402065,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5
2,SC444940,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5
3,SC857241,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4
4,11215147,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5
5,16519529,4.6,1.0,Great little country pub. Super staff / owners...,5 | 5 | 5 | 5 | 5
6,16379120,4.5,1.0,Very good food and taste Lovely lads from mir...,5 | 4 | 5 | 5 | 4
7,SC531326,4.6,2.0,We were intrigued by a face book post that Spi...,4 | 5 | 5 | 5 | 5
8,8589456,5.0,NaN,| |,5 | 5 | 5
9,15478214,4.6,NaN,I want to say how happy I am with Dobles. A co...,5 | 5 | 5 | 5 | 5

In [19]:
df1.isna().sum()

 CompanyNumber                          0
Google_Overall_Rating                   0
Google_Price_Level                  10290
Google_Review_Texts                    83
Google_Individual_Review_Ratings        9
dtype: int64

In [20]:
len(df1)

15659

In [21]:
df2 = pd.read_excel('Query_complete_03_06_26.xlsx')

In [22]:
df2.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,16113446,4.7,NaN,"Dear sir/madam, Just a brief note about your r...",4 | 5 | 5 | 5 | 5
1,15106345,2.5,NaN,Friendly and professional team with excellent ...,5 | 1 | 3 | 1
2,11826918,3.2,1.0,I don't know what happened to this place. It u...,2 | 5 | 1 | 1 | 5
3,14359046,4.7,NaN,Everything was amazing and the prices were gre...,5 | 4 | 5 | 5 | 4
4,15359174,4.5,NaN,Fine fusion is a great local restaurant. Start...,4 | 5 | 3 | 3 | 5

In [23]:
df2.isna().sum()

 CompanyNumber                         0
Google_Overall_Rating                  0
Google_Price_Level                  5664
Google_Review_Texts                   40
Google_Individual_Review_Ratings       2
dtype: int64

In [24]:
df2.isna().sum()

 CompanyNumber                         0
Google_Overall_Rating                  0
Google_Price_Level                  5664
Google_Review_Texts                   40
Google_Individual_Review_Ratings       2
dtype: int64

In [25]:
df2_sub1 = pd.read_excel('Quer_file_output_03_06_26.xlsx')

In [26]:
df2_sub1.head()

,CompanyNumber,BusinessName,PostCode,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,14584272,DOWNHAM KEBAB,BR14PP,4.2,1.0,"Ordered a chicken shish kebab with salad, pitt...",1 | 5 | 4 | 5 | 5
1,16673526,NEW CHINA COTTAGE,NN55BG,3.5,2.0,Have always used China Cottage in past which h...,1 | 2 | 5 | 1 | 1
2,15556160,KARACHI FLAVOURS,B128LG,4.7,NaN,Missing other Aloo parathas which was given on...,3 | 5 | 5 | 5 | 5
3,16950116,98 SIZZLE,B114DA,4.2,NaN,I’m the first one reviewing this shop. Their f...,5 | 4 | 5 | 5 | 5
4,16164579,PUNJABI DESI TADKA,SN11SG,4.7,NaN,"Amazing food, we ate in but probably better fo...",5 | 5 | 5 | 5 | 5

In [27]:
df2_sub1 = df2_sub1[[' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings']]

In [28]:
df2_sub1.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,14584272,4.2,1.0,"Ordered a chicken shish kebab with salad, pitt...",1 | 5 | 4 | 5 | 5
1,16673526,3.5,2.0,Have always used China Cottage in past which h...,1 | 2 | 5 | 1 | 1
2,15556160,4.7,NaN,Missing other Aloo parathas which was given on...,3 | 5 | 5 | 5 | 5
3,16950116,4.2,NaN,I’m the first one reviewing this shop. Their f...,5 | 4 | 5 | 5 | 5
4,16164579,4.7,NaN,"Amazing food, we ate in but probably better fo...",5 | 5 | 5 | 5 | 5

In [29]:
df2_sub1.isna().sum()

 CompanyNumber                        0
Google_Overall_Rating               520
Google_Price_Level                  811
Google_Review_Texts                 523
Google_Individual_Review_Ratings    521
dtype: int64

In [30]:
len(df2)

8681

In [31]:
len(df2_sub1)

928

In [32]:
df2_sub1 = df2_sub1.dropna(subset = ['Google_Overall_Rating'])

In [33]:
df2_sub1.isna().sum()

 CompanyNumber                        0
Google_Overall_Rating                 0
Google_Price_Level                  291
Google_Review_Texts                   3
Google_Individual_Review_Ratings      1
dtype: int64

In [34]:
len(df2_sub1)

408

In [35]:
final_df = pd.concat([df1,df2,df2_sub1])

In [36]:
len(final_df)

24748

In [37]:
final_df.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,Highly Recommended – M-Brothers Automotive Bri...,5 | 5 | 5 | 5 | 5
1,SC402065,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5
2,SC444940,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5
3,SC857241,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4
4,11215147,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5

In [38]:
master = pd.read_excel('Final Dataset.xlsx',sheet_name = 'Sheet1')

In [39]:
master.columns

Index([' CompanyNumber', 'CompanyName', 'RegAddress.CareOf',
       'RegAddress.AddressLine1', ' RegAddress.AddressLine2',
       'RegAddress.PostTown', 'RegAddress.County', 'RegAddress.Country',
       'RegAddress.PostCode', 'CompanyCategory', 'CompanyStatus',
       'Target Value', 'CountryOfOrigin', 'IncorporationDate',
       'Accounts.AccountRefDay', 'Accounts.AccountRefMonth',
       'Accounts.NextDueDate', 'Accounts.LastMadeUpDate',
       'Accounts.AccountCategory', 'Returns.NextDueDate',
       'Returns.LastMadeUpDate', 'Mortgages.NumMortCharges',
       'Mortgages.NumMortOutstanding', 'Mortgages.NumMortPartSatisfied',
       'Mortgages.NumMortSatisfied', 'SICCode.SicText_1', 'SICCode.SicText_2',
       'SICCode.SicText_3', 'SICCode.SicText_4',
       'LimitedPartnerships.NumGenPartners',
       'LimitedPartnerships.NumLimPartners', 'URI', 'PreviousName_1.CONDATE',
       ' PreviousName_1.CompanyName', ' PreviousName_2.CONDATE',
       ' PreviousName_2.CompanyName', 'PreviousName_3.CONDATE',
       ' PreviousName_3.CompanyName', 'PreviousName_4.CONDATE',
       ' PreviousName_4.CompanyName', 'PreviousName_5.CONDATE',
       ' PreviousName_5.CompanyName', 'PreviousName_6.CONDATE',
       ' PreviousName_6.CompanyName', 'PreviousName_7.CONDATE',
       ' PreviousName_7.CompanyName', 'ConfStmtNextDueDate',
       ' ConfStmtLastMadeUpDate', 'PostCode_Validity_x',
       'Potential_matches_name', 'Number of restaurants based on CH',
       'Potential_matches_address', 'Potential_matches_businessid',
       'Final_Business_ID', 'Single_remove', 'MatchScore',
       'Potential_Ownership_Change', 'Match_Method', 'AddressLine1',
       'AddressLine2', 'AddressLine3', 'AddressLine4', 'BusinessTypeID',
       'FHRSID', 'BusinessName', 'BusinessType', 'ConfidenceInManagement',
       'Hygiene', 'Latitude', 'LocalAuthorityBusinessID', 'LocalAuthorityCode',
       'LocalAuthorityName', 'Longitude', 'NewRatingPending', 'PostCode',
       'Number of restaurants in Postcode', 'RatingDate', 'RatingKey',
       'RatingValue', 'RightToReply', 'SchemeType', 'Structural',
       'PostCode_Validity_y'],
      dtype='object')

In [40]:
final_df[' CompanyNumber'] = final_df[' CompanyNumber'].astype(str).str.zfill(8)
master[' CompanyNumber'] = master[' CompanyNumber'].astype(str).str.zfill(8)

# 2. Perform the merge
df_combined = final_df.merge(master, on=' CompanyNumber', how='left')

In [41]:
len(df_combined)

24748

In [42]:
df_combined.to_excel('Merged_Final_Dataset.xlsx',index = False)